### ISSUE TITLE
Skin

### ISSUE THREAD

**Issue by WillSullivan** [WillSullivan/idownvotedbecause#1]
Ugly website is ugly

**Comment by WillSullivan** [comment]
I also noticed it's lousy on mobile.  Images blow out and the static margin don't work.  I'd prefer not to do something cheap like use bootstrap, but it might be a short term solution. That would become permanent after a couple days.

**Comment by j-f1** [comment]
[min](http://mincss.com)?

**Comment by WillSullivan** [comment]
Meh, might be something to build on... Not too bad with the mobile, tho.  Would have to try with images to see how well those are handled.
