### ISSUE TITLE
No evidence of research

### ISSUE THREAD

**Issue by mikemccaughan** [WillSullivan/idownvotedbecause#10]
I'd like to see a reason for a lack of research (or evidence thereof). It could expound on the various ways to show research without writing a novel, perhaps something about rubberducking as a form of research, etc.. I might have time later to fill this out, but thought I'd get the idea down in case someone else wants to take a stab.

**Comment by WillSullivan** [comment]
https://github.com/WillSullivan/idownvotedbecause/blob/master/stackoverflow/noresearch stubbed. Once completed, it needs an .md extension so Jekyll will compile it into the site.

**Comment by WillSullivan** [comment]
Moved to https://github.com/WillSullivan/idownvotedbecause/blob/master/_drafts/stackoverflow/noresearch.md because Jekyll
