### ISSUE TITLE
I won't be consise

### ISSUE THREAD

**Issue by boffi** [WillSullivan/idownvotedbecause#101]
_"Consise"_, as used in most of the (in every?) "Too Much ..." page(s) is wrong. The correct spelling is _"concise"_.

![consise](https://user-images.githubusercontent.com/2244221/45620549-9fd4c580-ba7d-11e8-9cb4-f0c318bc4397.png)

**Comment by Ashera138** [comment]
I could only find this spelling error in "toomuchcode.md", but I went ahead and changed it and submitted a PR. Thanks for pointing it out. 👍
