### ISSUE TITLE
Something for a "Please try the below" answers would be helpful

### ISSUE THREAD

**Issue by sonic1981** [WillSullivan/idownvotedbecause#105]
I see a lot of answers like this https://stackoverflow.com/a/52757560/542251

It'd be great if we could add a downvote reason that covers this. At the moment I'm using a comment:

> Please explain what you've changed and why. "Give this a go" answers are very unsatisfying. It forces everyone to; one, play spot the difference and two, then try and evaluate why you've changed what you've changed. It's much better if you tell us this up front.

It'd be great to expand on this. Thoughts?

**Comment by ghost** [comment]
It would be great! (Although I am a bit guilty of doing this myself)
It is annoying when someone takes somebody else's code and doesn't know how to modify it.
