### ISSUE TITLE
UnityEditor.BuildPlayerWindow+BuildMethodException: 2 errors   at UnityEditor.BuildPlayerWindow+DefaultBuildMethods.BuildPlayer (UnityEditor.BuildPlayerOptions options) [0x002bb] in

### ISSUE THREAD

**Issue by brawyo** [WillSullivan/idownvotedbecause#145]

**Comment by NateLevin1** [comment]
This is not stackoverflow, this is a repository for helping answerers of stackoverflow questions help those with flaws in their questions. Please [close this issue](https://stackoverflow.com/a/34010719/13608595) to help the maintainer.
