### ISSUE TITLE
Fix spelling of "Xcode"

### ISSUE THREAD

**Issue by paul-t-russell** [WillSullivan/idownvotedbecause#27]
This may seem trivial but it really grinds my gears - the correct spelling is [Xcode](https://developer.apple.com/xcode/).

**Comment by WillSullivan** [comment]
You know what grinds my gears? Unnecessary, counterproductive, unenforceable NDAs. But I fixed it anyhow :)

**Comment by paul-t-russell** [comment]
Thank you for respecting my inner pedant.  :)
