### ISSUE TITLE
Downvote reason for an answer ?

### ISSUE THREAD

**Issue by MickaelBaye** [WillSullivan/idownvotedbecause#31]
Hello there,

I'm wondering if we could create one reason (or more) reason for downvoting answers.
We have great reasons for downvoting a question on SO but **nothing for downvoting an answer**.
I think this could really help people improve their answer too.
This reason could be based on current [How do I write a good answer ?](https://stackoverflow.com/help/how-to-answer) on SO.

PS : This site is a really good idea :)

Regards.

**Comment by WillSullivan** [comment]
Absolutely!  I've got a few in mind, I just haven't gotten around to adding them.  If you want to share some, please feel free to do so here.

I'd like to add one for link-only answers, answers that are nothing but code, and answering blatantly off-topic questions.

**Comment by MickaelBaye** [comment]
Great! I think I'm going to start with with link-only answers.
I just saw one during a review.
I'll try to provide a first draft for this week.

I'm closing the issue as you answered my question.

**Comment by su-narthur** [comment]
@MickaelBaye You might consider adding separate issues for potential reasons.

**Comment by MickaelBaye** [comment]
I'm going to create an issue for each reason we talked about :
* link-only answer
* code-only answer
* answer for a blatantly off-topic question

**Comment by WillSullivan** [comment]
Yeesh, wrong place
