### ISSUE TITLE
Not quite ready

### ISSUE THREAD

**Issue by Narvey** [WillSullivan/idownvotedbecause#44]
This reason relies on people who post questions being instructed to wait for a few minutes after posting their question, since stuff happens quite fast on StackOverflow. However, this [hasn't happened yet](https://meta.stackoverflow.com/a/360371/1739000).

**Comment by Narvey** [comment]
Drats, your feedback link doesn't apply to specific pages.  The one I was referring to is http://iDownvotedBecau.se/BeingUnresponsive

**Comment by WillSullivan** [comment]
Well, I don't think it "relies" on this.  It's almost implied--why ask a question if you're not looking for answers? Are you going to ask a question then immediately board an 18 hour flight? I would like SO to remind new users to monitor their questions for comments asking for clarification, among other things. But that's on SO, not IDB. Upvoted your answer on the question.  

Also, the wording in that post stinks. Rewriting.
