### ISSUE TITLE
Bad title

### ISSUE THREAD

**Issue by adrianshum** [WillSullivan/idownvotedbecause#45]
Title of question should give a meaningful summary of the problem

Example of bad title
- Title that is simply meaningless (e.g. Java problem; Why the code fail)
- Title that is irrelevant to the actual problem
- Title that just describe the assignment or task, instead of the problem
  - e.g. https://stackoverflow.com/questions/45134675/sentence-builder-java
  - e.g. https://stackoverflow.com/questions/42499245/creating-a-guessing-game-in-c
- Title that requires special contextual knowledge of author (e.g. mentioning special jargons which is not meaningful for general public)

**Comment by Narvey** [comment]
That is an edit reason, not a downvote reason, right?

**Comment by WillSullivan** [comment]
Yes, I don't think this is a valid reason to downvote. It might be part of a larger problem that is, however. One where the question has many, many problems and is practically unsalvageable.
