### ISSUE TITLE
the how to debug should describe  gdb for c & c++ on linux

### ISSUE THREAD

**Issue by pm100** [WillSullivan/idownvotedbecause#46]

**Comment by WillSullivan** [comment]
Absolutely!  But since I don't code in the ghetto (god-tier C# here, sorry), I have no idea how to do this. If you could please submit a pull request including that info, I'd be more than glad to accept it :)

**Comment by pm100** [comment]
http://www.thegeekstuff.com/2010/03/debug-c-program-using-gdb/

**Comment by WillSullivan** [comment]
Done. Please view the changes in bf6c126f59e658f99458a1084764247a60b00952 and let me know if there are any problems. Thanks!
