### ISSUE TITLE
"Don't add code to comments" redundancy

### ISSUE THREAD

**Issue by remyabel** [WillSullivan/idownvotedbecause#53]
There are three pages that mention not adding code to comments:

- http://idownvotedbecau.se/nodebugging/

- http://idownvotedbecau.se/nocode/

- http://idownvotedbecau.se/imageofanexception/

I think it breaks the flow and is a little redundant. However, the paragraphs all contain useful information so maybe they can be factored out into a separate page or [admonition](http://docutils.sourceforge.net/docs/ref/rst/directives.html#admonitions). Something like:

> When requested to add code or stack traces to your question, please do not paste them in the comments. Instead, use the **Edit** link found below your question. Comments are meant to be [brief](https://meta.stackexchange.com/questions/39260/how-do-i-post-code-in-comments/39264#39264) and cannot format code as neatly.

**Comment by WillSullivan** [comment]
Honestly, I don't think that's much of an issue.  They're all related subjects.  In fact, if you combed through many pages you'll find similar redundancies.  Keeping all the information related to what the user needs to know on one page is important.  We already are asking them to click through once for the information they need, and people already have a problem with _that_ (too lazy to link to various meta discussions on the subject)...
