### ISSUE TITLE
The "it's not working" is to focused on code

### ISSUE THREAD

**Issue by klutt** [WillSullivan/idownvotedbecause#56]
"it's not working" is to focused on code. I think it should be rewritten to be more general. I realized that now, when I answered someone who was trying to compile working code. I think I'll try to make a suggestion later, but I wanted to point this out. Not all programming problems is directly related to the code.

**Comment by WillSullivan** [comment]
Not sure what you mean, but if you add a pull request I'll definitely check it out.

**Comment by LindaLawton** [comment]
I think i can almost see their point with this one.    It is possible to be installing say Visual studio and it not be working.   It could also be possible to be deploying something and it not be working.   Neither really have anything to do with code.

The page could be reworked to not be code related.

**Comment by klutt** [comment]
LindaLawton nailed my point exactly.

**Comment by LindaLawton** [comment]
you want to give a shot at rewording it or shall I?

**Comment by WillSullivan** [comment]
Well, I don't want to see all code related stuff removed. I'd wager north of 90% of "not working" questions *are* code related. But a section about other things "not working" could be added, perhaps above the details about code? I'll entertain all PRs. Thanks.

**Comment by klutt** [comment]
LindaLawton: Feel free

**Comment by WillSullivan** [comment]
Hey yall, check out the pull I just completed. It's got an extra paragraph about the NPR issues. If you'd like more added to it, feel free to suggest!
