### ISSUE TITLE
Image Of code 

### ISSUE THREAD

**Issue by LindaLawton** [WillSullivan/idownvotedbecause#58]
[I downvoted because an image of your code is not helpful](http://idownvotedbecau.se/imageofcode)

Could possibly use an example.   Showing say screenshot of code, and well formatted example of code.

Also might not be a bad idea to have this refer to links of images hosted on other sites like image shack with just links to them.   Something like please include your pictures rather than linking to your pictures.   However this may actually be a separate problem.

I am happy to take some ugly pictures from Visual studio and add a pull request if you like.

**Comment by WillSullivan** [comment]
Sounds good. Make sure to include some freehand circles, thx.

**Comment by LindaLawton** [comment]
I could use a tip what do you use to edit these files?   NotePad++?

**Comment by LindaLawton** [comment]
Hows this for ugly [My fork](https://github.com/LindaLawton/idownvotedbecause/blob/master/stackoverflow/imageofcode.md)

**Comment by WillSullivan** [comment]
I usually edit them here, or I'll pull them down and work them in VS Code. 

I'll have to come back to this sometime tomorrow. Thanks!

**Comment by LindaLawton** [comment]
Did you have a chance to check my fork?

**Comment by WillSullivan** [comment]
Sorry, getting pulled in different directions lately. The fork looks good. Send a pull request and I'll close this out.

**Comment by LindaLawton** [comment]
For an open source project getting to many pull requests to handle is a really good sign :)

**Comment by WillSullivan** [comment]
Closing with #60
