### ISSUE TITLE
Too much code vs too much info

### ISSUE THREAD

**Issue by LindaLawton** [WillSullivan/idownvotedbecause#59]
I am wondering if this could be reworded to also include wall of text type question as seen below.

[Wall of text example](https://stackoverflow.com/q/48454903/1841839)

**Comment by WillSullivan** [comment]
It's entirely possible to create a new page that concentrates on situations like the above, highlighting the "concisely detail what you have done, what was the result, and why that does not work for you" mantra. Adding a reference to "keep code to the bare minimum" and "keep your browser tab open and check on your question often to add additional details as requested" side notes would be nice.

**Comment by LindaLawton** [comment]
my main worry is creating to many pages vs being to general.    I only ran across your project last week so can only speak of my experience of using it over the last week.     its been great but if we end up with to many pages it will be hard to remember them all.

**Comment by WillSullivan** [comment]
Merged and closed. Thanks for the addition.
