### ISSUE TITLE
noattempt should possibly link to noresearch

### ISSUE THREAD

**Issue by LindaLawton** [WillSullivan/idownvotedbecause#61]
I find my self commenting with something along these lines.

idownvotedbecau.se/noattempt && idownvotedbecau.se/noresearch  

[see](https://stackoverflow.com/q/48536426/1841839)  the poster made no attempt to use the code from within the duplicate and didn't bother to research what he was trying to do.

I am wondering if maybe there should be a comment in no attempt about doing research?

**Comment by WillSullivan** [comment]
Took a stab at it with 5b761abea8fb7a16acbd9a57b498e3ac66e3a01e what do you think?

**Comment by LindaLawton** [comment]
comments inline :)

**Comment by LindaLawton** [comment]
Did we resolve this?

**Comment by WillSullivan** [comment]
Well, the link was added, so I'm going to say yes.
