### ISSUE TITLE
Delete draft Off topic answer

### ISSUE THREAD

**Issue by LindaLawton** [WillSullivan/idownvotedbecause#67]
I would like to suggest that we delete the draft [Off topic answer](https://github.com/WillSullivan/idownvotedbecause/blob/master/_drafts/stackoverflow/responseofftopic.md)  

I cant exactly understand the purpose of it.

1.  If the answer itself is off topic and has nothing to do with the question asked?  
 a.  Answer should be flagged and deleted not just down voted and theirs probably nothing they can do to fix it.  So what is the point of us having a page for it?   
 b. IMO these pages should be used to help users fix there issues not just slap them on the wrist.
2.  Someone answered an off topic question.  
  a. Well if you want to spend your time answering an off topic question that will probably be close then all power to you. 
   b.  It may just be the right answer and there for i wouldn't down vote you for your efforts. 

So do we need this page?

**Comment by LindaLawton** [comment]
Is it worth down voting a code only answer?   If the code is works and is correct while i agree not explaining the solution is a problem but is it really worth a down vote?

[Code Only](https://github.com/WillSullivan/idownvotedbecause/blob/master/_drafts/stackoverflow/responseonlycode.md)

I guess i am having an issue with the purpose of some of these drafts.

**Comment by WillSullivan** [comment]
Well, there's a reason why they're in drafts... I pretty much agree with you on code only answers, but there are plenty of folks who do consider that bad practice and want to downvote to discourage it. 

As for the off topic question, I disagree with deleting it. The specific purpose is to let people know that answering blatantly off topic questions is a bad thing. It encourages them, which is inconsiderate to the community. How informing the user of this via idvb is not just to get them to delete (thus getting back their rep) but also to encourage them to understand what is and is not on topic, and to join the community redirecting or closing and deleting off topic questions. "Delete your answer" isn't enough to justify the page, I agree. It's the other stuff that I think makes a page for it worthwhile.

**Comment by LindaLawton** [comment]
I can try to improve them both to the point that they arnt condescending and we can leave them if you like.   No one says i have to personally use them :)
