### ISSUE TITLE
Add a page for "Unclear what you're asking"

### ISSUE THREAD

**Issue by jdgregson** [WillSullivan/idownvotedbecause#70]
The most common reason I flag something is because it is unclear what the OP is actually asking, so it would be helpful to have "unclear what you're asking" as an option on idownvotedbecause. Or should such questions always be flagged and closed as soon as possible without feedback for the user?

**Comment by LindaLawton** [comment]
I am going to give him a bit to create a pull request on it.   If he doesn't do you want to create one yourself?

**Comment by WillSullivan** [comment]
I actually don't know how to create a pull request on someone else's repo. Ball's in @jdgregson's court for now.

**Comment by LindaLawton** [comment]
@WillSullivan  i dont think you can i can fork his repo and make my changes then apply a pull request to him.  Hes still going to have to create a pull request to this.   

So basically I suggest we give him a few more days then I will just copy his stuff make a new branch and an pull request for that on this.

**Comment by LindaLawton** [comment]
I think we waited long enough.   I copied it but noted that the primary version came from him.

**Comment by Ashera138** [comment]
Should this be closed now?

**Comment by WillSullivan** [comment]
Yep!
