### ISSUE TITLE
missing word in sentence (noattempt)

### ISSUE THREAD

**Issue by sapientN3T** [WillSullivan/idownvotedbecause#75]
The following sentence is missing a word:

"If we have made an effort, but we failed to detail exactly what we did in our question can result in duplicated effort on the part of those trying to help us."

Suggested fix:

"If we have made an effort, but we failed to detail exactly what we did in our question, that can result in duplicated effort on the part of those trying to help us."

**Comment by LindaLawton** [comment]
How about 

It can result in

**Comment by WillSullivan** [comment]
Fixed. Thanks.
