### ISSUE TITLE
Clunky sentence in MCVE

### ISSUE THREAD

**Issue by sonic1981** [WillSullivan/idownvotedbecause#78]
The sentence:

> If lacking the code that exhibits the issue...

in the paragraph of *Why this is a problem* is a bit clunky to me. Could do with being slightly re-worded to be a bit clearer. i.e.

> If you post code and that code is lacking the section of code that actually exhibits the issue....

So full paragraph:

> Without code, users will have to guess what might be wrong with a person’s code. With too much code, the problem may be lost like the proverbial needle in the haystack. If you post code and that code is lacking the section of code that actually exhibits the issue, then what is included is practically worthless. And, if the code is full of compile errors or artificial bugs caused by translation to the question, these may hide the actual problem.

**Comment by LindaLawton** [comment]
Works for me feel free to submit a pull request.

**Comment by sonic1981** [comment]
Just thought have I merged that into the right branch? Or do you want it to go straight into master?

**Comment by LindaLawton** [comment]
no idea that why I left it wait for directions :)

**Comment by Ashera138** [comment]
This issue can be closed now. 👍
