### ISSUE TITLE
Wrong language

### ISSUE THREAD

**Issue by Blacksilver42** [WillSullivan/idownvotedbecause#80]
I was doin' the triage queue, no sweat, when I came across a question written in Portugese.

I wanted to downvote and link to a relevant idownvotedbecau.se page for "wrong language", but, well, there isn't one.

Hence, this issue.

This page might need a little extra doing, which is why I don't just make a PR: There should be different versions for each language. e.g., `idownvotedbecau.se/wronglanguage/?lang=fr` should serve up the page, in french.

**Comment by LindaLawton** [comment]
I think its a good idea but i dont think we can handle multiple languages i think it would be to hard.  Just a general one in English should be good enough

**Comment by Blacksilver42** [comment]
Start with that; put the multiple languages thing on the long-term TODO.

**Comment by WillSullivan** [comment]
It'll probably break the normal format, which might be appropriate in this case. Move the current headers down a notch and add a new top level header for the language, then keep each section short as possible because it'll get repeated in multiple different languages.

**Comment by Blacksilver42** [comment]
We should put "Translate the whole site" on The List™️

**Comment by Blacksilver42** [comment]
I've [created a fork](https://github.com/Blacksilver42/idownvotedbecause/blob/master/stackoverflow/wronglanguage.md).

**Comment by Ashera138** [comment]
I submitted a PR for the base page in English. I'm not sure what you guys had in mind for adding other languages. I could cover a Spanish translation if you have an idea of how you want it.
