### ISSUE TITLE
https

### ISSUE THREAD

**Issue by Blacksilver42** [WillSullivan/idownvotedbecause#84]
https://blog.github.com/2018-05-01-github-pages-custom-domains-https/

**Comment by WillSullivan** [comment]
They're generating the cert for the site now. Next steps are to verify it works, enforce, and then update http links to https.

**Comment by WillSullivan** [comment]
No go. Claims I'm not configured correctly. Sent support my DNS records and asked for help.

**Comment by Blacksilver42** [comment]
Wow, this issue is still open? \*poke\*

**Comment by WillSullivan** [comment]
https://idownvotedbecau.se/ it's working now. Might be some http:// links here or there in the pages, but a cursory look doesn't reveal any. Now I'm going back to sleep.
