### ISSUE TITLE
Too much code page is a bit passive agressive and contains pronouns

### ISSUE THREAD

**Issue by sonic1981** [WillSullivan/idownvotedbecause#85]
Some of the wording in http://idownvotedbecau.se/toomuchcode/:

> It also shows that not much effort was put into creating **your** question. People are volunteering their time, free of charge, to help **you**. **You** need to be considerate of their efforts. One of the easiest, and most helpful, ways to do this is to pare down **your** code to the minimum needed to illustrate **your** problem.

Is a but preachy and passive aggressive. It also contains the pronouns "_your_" and "_you_" . If you compare it to similar sentences on no attempt:

> It can be seen as very rude to ask other people to do our work for us. People will look and see if we made any effort at all, and if they see none, they may look upon us as lazy, and act negatively toward us, downvoting our question and voting to close. Without making an attempt, we may not even know where our real problem lies. People may spend time answering our question, suggesting things that we would have already been able to accomplish, and not things that we truly would have needed help with. This wastes the time of those volunteering to help us, and doesn’t solve our problem at all.

This is a bit more passive (without the aggressive!). I'd suggest changing the wording in this area to be more in line with the other more passive, less aggressive pages?

**Comment by Ashera138** [comment]
It looks like this can be closed now.

I'm going to open a separate issue for the "TooMuchInfo" page because it has a lot of the same issues (even some of the same text that was copy-pasted).

**Comment by WillSullivan** [comment]
Kk thx
