### ISSUE TITLE
HomePage empty with no information

### ISSUE THREAD

**Issue by karan-shishoo** [WillSullivan/idownvotedbecause#86]
First off wonderful resource. Only issue that I had was that http://idownvotedbecau.se/ only has a banner (which links back to itself) while http://idownvotedbecau.se/index has all the needed information about the website. To anyone not too familiar websites it may be confusing for them to navigate and access all the pages/resources on the site as the first page linked by google is http://idownvotedbecau.se/ and not the index/help page

**Comment by WillSullivan** [comment]
Thanks. I'm not sure what you mean, tho... If you go to https://idownvotedbecau.se/ it automatically serves the content in index.md.  https://idownvotedbecau.se/index shows the same content, of course. 

What browser are you using?

**Comment by karan-shishoo** [comment]
![image](https://user-images.githubusercontent.com/23003030/40700700-45aaec82-63f8-11e8-8321-636a24476bbc.png)

I attached a screenshot, using chrome on windows 7

**Comment by WillSullivan** [comment]
No repro, either way. Tried in Edge, chrome, both http and https.  Check your console for error messages? Clear your cache?

**Comment by karan-shishoo** [comment]
I guess it was due to something random as when I inspected the page as I loaded it, it had the expected behaviour. No error messages (cache was cleared last time i tried).
