### ISSUE TITLE
Is it possible to add routes to allow for capitalized names.

### ISSUE THREAD

**Issue by leftler** [WillSullivan/idownvotedbecause#9]
Having additional routes to the existing pages so that `http://idownvotedbecau.se/nocode/` and `http://idownvotedbecau.se/NoCode/` both worked would be nice to have.

**Comment by WillSullivan** [comment]
Might be possible.  Gonna take a sec and see if I can get https://github.com/jekyll/jekyll-redirect-from working for that example...

**Comment by WillSullivan** [comment]
Yes!  I've updated the template with the redirect yaml and added a few alternatives for all the current pages.
